import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import {routes, aliases, preferredLanguage, localizedPath} from '../i18n/routes.mjs';
import {messages,reasonPatterns,monthNames} from '../i18n/messages.mjs';
import {withGtm} from './gtm.mjs';
const origin='https://tennoro.com';
const catalogs=Object.fromEntries(['fr','en'].map(lang=>[lang,JSON.parse(readFileSync(`i18n/${lang}.json`,'utf8'))]));
if(JSON.stringify(Object.keys(catalogs.fr).sort())!==JSON.stringify(Object.keys(catalogs.en).sort()))throw Error('Static translation keys differ');
if(JSON.stringify(Object.keys(messages.fr).sort())!==JSON.stringify(Object.keys(messages.en).sort()))throw Error('Runtime translation keys differ');
function write(path,content){mkdirSync(dirname(path),{recursive:true});writeFileSync(path,content);}
const escape=s=>s.replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const alternates=route=>`<link rel="alternate" hreflang="fr" href="${origin}/fr/${route}" />\n<link rel="alternate" hreflang="en" href="${origin}/en/${route}" />\n<link rel="alternate" hreflang="x-default" href="${origin}/${route}" />`;
const pagePath=(lang,route)=>`${lang}/${route}${route===''||route.endsWith('/')?'index.html':''}`;
for(const lang of ['fr','en']){
 const data={messages:messages[lang],months:monthNames[lang],frMonths:monthNames.fr,reasonPatterns};
 write(`i18n/catalog.${lang}.js`,'// Generated by scripts/build-i18n.mjs\nwindow.TENNORO_TRANSLATIONS = '+JSON.stringify(data).replaceAll('<','\\u003c')+';\n');
 for(const [page,route]of Object.entries(routes)){
  let html=readFileSync(`i18n/templates/${page}.html`,'utf8');
  html=html.replace(/\{\{(\w+)\}\}/g,(_,key)=>{if(!(key in catalogs[lang]))throw Error('Missing '+lang+':'+key);return escape(catalogs[lang][key]);});
  html=html.replace('<html lang="fr">',`<html lang="${lang}">`);
  html=html.replace(/(<link rel="canonical" href=")[^"]+/,`$1${origin}/${lang}/${route}`);
  html=html.replace(/(<meta property="og:url" content=")[^"]+/,`$1${origin}/${lang}/${route}`);
  html=html.replace('content="fr_FR"',`content="${lang==='fr'?'fr_FR':'en_GB'}"`);
  html=html.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(_,json)=>{
    const data=JSON.parse(json);for(const entity of data['@graph']||[]){if(entity['@type']==='WebSite'){entity.inLanguage=lang;entity.url=`${origin}/${lang}/`;entity['@id']=entity.url+'#website';}}
    return '<script type="application/ld+json">'+JSON.stringify(data,null,2)+'</script>';
  });
  html=html.replace(/href="(\/[^"#?]*)([^\"]*)"/g,(full,path,tail)=>{
    const normalized=path.replace(/index\.html$/,'');
    return Object.values(routes).includes(normalized.slice(1))?`href="/${lang}${normalized}${tail}"`:full;
  });
  const selector=`<div class="language-switch" role="group" aria-label="${messages[lang].language}">${['fr','en'].map(l=>`<a href="/${l}/${route}" lang="${l}" hreflang="${l}" data-language="${l}"${l===lang?' aria-current="true"':''}>${l.toUpperCase()}</a>`).join('<span aria-hidden="true">/</span>')}</div>`;
  html=html.replace(/(<a class="nav-cta"[^>]*>[\s\S]*?<\/a>)/,`<div class="nav-actions">$1${selector}</div>`);
  html=html.replace('</head>',`${alternates(route)}\n<link rel="stylesheet" href="/i18n/languages.css" />\n<script src="/i18n/catalog.${lang}.js"></script>\n<script src="/i18n/runtime.js"></script>\n</head>`);
  write(pagePath(lang,route),'<!-- Generated: edit i18n/templates and i18n catalogs, then run node scripts/build-i18n.mjs -->\n'+withGtm(html));
 }
}
function redirect(route){
 const redirectScript=`(()=>{const aliases=${JSON.stringify(aliases)};${preferredLanguage.toString()};${localizedPath.toString()};let saved=null;try{saved=localStorage.getItem('tennoro-language');}catch{}const explicit=location.pathname.match(/^\\/(fr|en)(?:\\/|$)/)?.[1];const lang=explicit||preferredLanguage(saved,navigator.language);const target=localizedPath(location.pathname,lang)+location.search+location.hash;if(target!==location.pathname+location.search+location.hash)location.replace(target);})();`;
 return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
<script>${redirectScript}</script>
<title>${messages.en.redirectTitle}</title>
${alternates(route)}
<style>html{background:#080808;color:#fff}</style>
<noscript>
<link rel="stylesheet" href="/styles.css" />
</noscript>
</head><body><noscript><main class="container" style="padding-top:120px;text-align:center">
<h1 style="font-size:2rem">${messages.en.redirect} / <span lang="fr">${messages.fr.redirect}</span></h1>
<p><a class="button button-secondary" href="/fr/${route}" data-language="fr" lang="fr">FR — Français</a> <a class="button button-secondary" href="/en/${route}" data-language="en" lang="en">EN — English</a></p>
</main></noscript></body></html>\n`;
}
for(const route of Object.values(routes))write(route===''?'index.html':route.endsWith('/')?route+'index.html':route,redirect(route));
for(const [alias,target]of Object.entries(aliases)){
 if(alias==='index.html')continue;
 write(alias.endsWith('/')?alias+'index.html':alias,redirect(target));
 // Explicit-language legacy aliases never use browser detection.
 for(const lang of ['fr','en'])write(pagePath(lang,alias),redirect(target));
}
const urls=Object.values(routes).flatMap(route=>['fr','en'].map(lang=>`  <url><loc>${origin}/${lang}/${route}</loc><xhtml:link rel="alternate" hreflang="fr" href="${origin}/fr/${route}"/><xhtml:link rel="alternate" hreflang="en" href="${origin}/en/${route}"/><xhtml:link rel="alternate" hreflang="x-default" href="${origin}/${route}"/></url>`));
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'+urls.join('\n')+'\n</urlset>\n');
console.log('Built 12 localized pages, locale entry points, shared runtime catalogs and sitemap.');
